### ISSUE TITLE
Cannot read property 'substr' of undefined

### ISSUE THREAD

**Issue by steebchen** [pascalgn/size-label-action#5]
I was creating a PR as usualy and then this happened:

```
Step 8/8 : ENTRYPOINT [ "size-label-action" ]
 ---> Using cache
 ---> db0b7ef7ec4a
Successfully built db0b7ef7ec4a
Successfully tagged gcr.io/gct-12-31z7i2ekvasojsdcoax56id/ce30ef9e153af8851e964b872099a731d968b5cd4642ad5077c457b327fdc6a7/8a5edab282632443219e051e4ade2d1d5bbc671c781051bf1437897cbdfea0f1:e1d15c83907c79250b9835f874517f7978e0dc88e0b97f250dd877c2b304f473
Already have image (with digest): gcr.io/github-actions-images/action-runner:latest
TypeError: Cannot read property 'substr' of undefined
    at isIgnored (/usr/local/share/.config/yarn/global/node_modules/size-label-action/index.js:121:27)
    at Diff.parsePatch.flatMap.file (/usr/local/share/.config/yarn/global/node_modules/size-label-action/index.js:152:7)
    at Array.flatMap (<anonymous>)
    at getChangedLines (/usr/local/share/.config/yarn/global/node_modules/size-label-action/index.js:151:6)
    at main (/usr/local/share/.config/yarn/global/node_modules/size-label-action/index.js:70:24)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

### FAILED assign size labels 16:40:45Z (10.521s)
```

**Comment by pascalgn** [comment]
Yeah, sorry, it's a bug 😞 

The good news is that it's already fixed, though, so if you update your workflow file to have
```
uses = "pascalgn/size-label-action@d728e8ec38381be59961fd6d10d8bf3c53f5f38d"
```
it should be working again! 👍

**Comment by steebchen** [comment]
Upgraded to the latest version, so I'm closing this for now.
